---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dns-cs-sap-com-v1alpha1-masqueradingrule
  failurePolicy: Fail
  name: mmasqueradingrule.kb.io
  rules:
  - apiGroups:
    - dns.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - masqueradingrules
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dns-cs-sap-com-v1alpha1-masqueradingrule
  failurePolicy: Fail
  name: vmasqueradingrule.kb.io
  rules:
  - apiGroups:
    - dns.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - masqueradingrules
  sideEffects: None
