# permissions for end users to edit masqueradingrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: masqueradingrule-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dns-masquerading-operator
    app.kubernetes.io/part-of: dns-masquerading-operator
    app.kubernetes.io/managed-by: kustomize
  name: masqueradingrule-editor-role
rules:
- apiGroups:
  - dns.cs.sap.com
  resources:
  - masqueradingrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.cs.sap.com
  resources:
  - masqueradingrules/status
  verbs:
  - get
