/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and dns-masquerading-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisdnscssapcomv1alpha1 "github.com/sap/dns-masquerading-operator/api/v1alpha1"
	versioned "github.com/sap/dns-masquerading-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/sap/dns-masquerading-operator/pkg/client/informers/externalversions/internalinterfaces"
	dnscssapcomv1alpha1 "github.com/sap/dns-masquerading-operator/pkg/client/listers/dns.cs.sap.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MasqueradingRuleInformer provides access to a shared informer and lister for
// Masqueradingrules.
type MasqueradingRuleInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() dnscssapcomv1alpha1.MasqueradingRuleLister
}

type masqueradingRuleInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMasqueradingRuleInformer constructs a new informer for MasqueradingRule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMasqueradingRuleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewMasqueradingRuleInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewFilteredMasqueradingRuleInformer constructs a new informer for MasqueradingRule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMasqueradingRuleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewMasqueradingRuleInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewMasqueradingRuleInformerWithOptions constructs a new informer for MasqueradingRule type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMasqueradingRuleInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	gvr := schema.GroupVersionResource{Group: "dns.cs.sap.com", Version: "v1alpha1", Resource: "masqueradingrules"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.DnsV1alpha1().Masqueradingrules(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.DnsV1alpha1().Masqueradingrules(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.DnsV1alpha1().Masqueradingrules(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.DnsV1alpha1().Masqueradingrules(namespace).Watch(ctx, opts)
			},
		}, client),
		&apisdnscssapcomv1alpha1.MasqueradingRule{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	)
}

func (f *masqueradingRuleInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewMasqueradingRuleInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *masqueradingRuleInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisdnscssapcomv1alpha1.MasqueradingRule{}, f.defaultInformer)
}

func (f *masqueradingRuleInformer) Lister() dnscssapcomv1alpha1.MasqueradingRuleLister {
	return dnscssapcomv1alpha1.NewMasqueradingRuleLister(f.Informer().GetIndexer())
}
