/*
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and dns-masquerading-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	dnscssapcomv1alpha1 "github.com/sap/dns-masquerading-operator/api/v1alpha1"
	versioned "github.com/sap/dns-masquerading-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/sap/dns-masquerading-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/sap/dns-masquerading-operator/pkg/client/listers/dns.cs.sap.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MasqueradingRuleInformer provides access to a shared informer and lister for
// MasqueradingRules.
type MasqueradingRuleInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.MasqueradingRuleLister
}

type masqueradingRuleInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMasqueradingRuleInformer constructs a new informer for MasqueradingRule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMasqueradingRuleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMasqueradingRuleInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMasqueradingRuleInformer constructs a new informer for MasqueradingRule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMasqueradingRuleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DnsV1alpha1().MasqueradingRules(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DnsV1alpha1().MasqueradingRules(namespace).Watch(context.TODO(), options)
			},
		},
		&dnscssapcomv1alpha1.MasqueradingRule{},
		resyncPeriod,
		indexers,
	)
}

func (f *masqueradingRuleInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMasqueradingRuleInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *masqueradingRuleInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&dnscssapcomv1alpha1.MasqueradingRule{}, f.defaultInformer)
}

func (f *masqueradingRuleInformer) Lister() v1alpha1.MasqueradingRuleLister {
	return v1alpha1.NewMasqueradingRuleLister(f.Informer().GetIndexer())
}
