/*
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and dns-masquerading-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// MasqueradingRuleListerExpansion allows custom methods to be added to
// MasqueradingRuleLister.
type MasqueradingRuleListerExpansion interface{}

// MasqueradingRuleNamespaceListerExpansion allows custom methods to be added to
// MasqueradingRuleNamespaceLister.
type MasqueradingRuleNamespaceListerExpansion interface{}
