/*
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and dns-masquerading-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	dnscssapcomv1alpha1 "github.com/sap/dns-masquerading-operator/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MasqueradingRuleLister helps list Masqueradingrules.
// All objects returned here must be treated as read-only.
type MasqueradingRuleLister interface {
	// List lists all Masqueradingrules in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*dnscssapcomv1alpha1.MasqueradingRule, err error)
	// Masqueradingrules returns an object that can list and get Masqueradingrules.
	Masqueradingrules(namespace string) MasqueradingRuleNamespaceLister
	MasqueradingRuleListerExpansion
}

// masqueradingRuleLister implements the MasqueradingRuleLister interface.
type masqueradingRuleLister struct {
	listers.ResourceIndexer[*dnscssapcomv1alpha1.MasqueradingRule]
}

// NewMasqueradingRuleLister returns a new MasqueradingRuleLister.
func NewMasqueradingRuleLister(indexer cache.Indexer) MasqueradingRuleLister {
	return &masqueradingRuleLister{listers.New[*dnscssapcomv1alpha1.MasqueradingRule](indexer, dnscssapcomv1alpha1.Resource("masqueradingrule"))}
}

// Masqueradingrules returns an object that can list and get Masqueradingrules.
func (s *masqueradingRuleLister) Masqueradingrules(namespace string) MasqueradingRuleNamespaceLister {
	return masqueradingRuleNamespaceLister{listers.NewNamespaced[*dnscssapcomv1alpha1.MasqueradingRule](s.ResourceIndexer, namespace)}
}

// MasqueradingRuleNamespaceLister helps list and get Masqueradingrules.
// All objects returned here must be treated as read-only.
type MasqueradingRuleNamespaceLister interface {
	// List lists all Masqueradingrules in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*dnscssapcomv1alpha1.MasqueradingRule, err error)
	// Get retrieves the MasqueradingRule from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*dnscssapcomv1alpha1.MasqueradingRule, error)
	MasqueradingRuleNamespaceListerExpansion
}

// masqueradingRuleNamespaceLister implements the MasqueradingRuleNamespaceLister
// interface.
type masqueradingRuleNamespaceLister struct {
	listers.ResourceIndexer[*dnscssapcomv1alpha1.MasqueradingRule]
}
